// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieReservation.Data.DbContexts;

#nullable disable

namespace MovieReservation.Migrations
{
    [DbContext(typeof(MovieReservationDbContext))]
    [Migration("20241024231354_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK_user_id");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "someEmail@localhost.com",
                            FirstName = "root",
                            LastName = "root",
                            Password = "AQAAAAIAAYagAAAAEAY1R2rYFTuAfnJQtaN1KlahqJMGauvaXaBW5cv0Qw3nmcGdIFKoo6HWXtLvQ2JiAg==",
                            Role = "Admin",
                            Username = "root"
                        });
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Auditorium", b =>
                {
                    b.Property<string>("AuditoriumNumber")
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("auditorium_number");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("max_capacity");

                    b.HasKey("AuditoriumNumber")
                        .HasName("PK_auditorium_number");

                    b.HasIndex("LocationId");

                    b.ToTable("Auditoriums", null, t =>
                        {
                            t.HasCheckConstraint("CK_max_capacity", "max_capacity > 0");
                        });
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("State")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("street");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("zip")
                        .IsFixedLength();

                    b.HasKey("LocationId")
                        .HasName("PK_location_id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("genre");

                    b.Property<string>("PosterImageName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("poster_image_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("title");

                    b.HasKey("MovieId")
                        .HasName("PK_movie_id");

                    b.HasIndex("Genre");

                    b.HasIndex("Title");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime?>("DateCancelled")
                        .HasColumnType("DATETIME")
                        .HasColumnName("date_cancelled");

                    b.Property<DateTime>("DateReserved")
                        .HasColumnType("DATETIME")
                        .HasColumnName("date_reserved");

                    b.Property<decimal>("Total")
                        .HasColumnType("MONEY")
                        .HasColumnName("total");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReservationId")
                        .HasName("PK_reservation_id");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<string>("AuditoriumNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("auditorium_number");

                    b.Property<decimal>("Price")
                        .HasColumnType("MONEY")
                        .HasColumnName("price");

                    b.HasKey("SeatId")
                        .HasName("PK_seat_id");

                    b.HasIndex("AuditoriumNumber");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Showing", b =>
                {
                    b.Property<int>("ShowingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("showing_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowingId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME")
                        .HasColumnName("date");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.HasKey("ShowingId")
                        .HasName("PK_showing_id");

                    b.HasIndex("MovieId");

                    b.ToTable("Showings");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.ShowingSeat", b =>
                {
                    b.Property<int>("ShowingSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("showing_seat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowingSeatId"));

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.Property<int>("ShowingId")
                        .HasColumnType("int")
                        .HasColumnName("showing_id");

                    b.HasKey("ShowingSeatId")
                        .HasName("PK_showing_seat_id");

                    b.HasIndex("SeatId");

                    b.HasIndex("ShowingId");

                    b.ToTable("ShowingSeats");
                });

            modelBuilder.Entity("ReservedSeats", b =>
                {
                    b.Property<int>("ShowingSeatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("showing_seat_id");

                    b.Property<int>("ReservationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reservation_id");

                    b.HasKey("ShowingSeatId", "ReservationId")
                        .HasName("PK_showingseat_reservation");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservedSeats");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Auditorium", b =>
                {
                    b.HasOne("MovieReservation.Infrastructure.Models.Location", "Location")
                        .WithMany("Auditoriums")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_auditorium_location");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Reservation", b =>
                {
                    b.HasOne("MovieReservation.Infrastructure.Models.AppUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_app_user_reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Seat", b =>
                {
                    b.HasOne("MovieReservation.Infrastructure.Models.Auditorium", "Auditorium")
                        .WithMany("Seats")
                        .HasForeignKey("AuditoriumNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_seat_auditorium");

                    b.Navigation("Auditorium");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Showing", b =>
                {
                    b.HasOne("MovieReservation.Infrastructure.Models.Movie", "Movie")
                        .WithMany("Showings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_movie_showing");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.ShowingSeat", b =>
                {
                    b.HasOne("MovieReservation.Infrastructure.Models.Seat", "Seat")
                        .WithMany("ShowingSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_showing_seat_seat");

                    b.HasOne("MovieReservation.Infrastructure.Models.Showing", "Showing")
                        .WithMany("ShowingSeats")
                        .HasForeignKey("ShowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_showing_seat_showing");

                    b.Navigation("Seat");

                    b.Navigation("Showing");
                });

            modelBuilder.Entity("ReservedSeats", b =>
                {
                    b.HasOne("MovieReservation.Infrastructure.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieReservation.Infrastructure.Models.ShowingSeat", null)
                        .WithMany()
                        .HasForeignKey("ShowingSeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.AppUser", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Auditorium", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Location", b =>
                {
                    b.Navigation("Auditoriums");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Movie", b =>
                {
                    b.Navigation("Showings");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Seat", b =>
                {
                    b.Navigation("ShowingSeats");
                });

            modelBuilder.Entity("MovieReservation.Infrastructure.Models.Showing", b =>
                {
                    b.Navigation("ShowingSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
